ラジオボタンのコンポーネントの作成
KadoProG/diary-vba-web pull request #1
Opened 2023-03-02 22:51 UTC by KadoProG

ラジオボタンで項目を選択させるコンポーネントを作成したのですが、
- コンポーネントに返り値という概念があるか
- idやhtmlForの使い方が正しいか
というのを確認してほしいです

2023-03-03 00:24 UTC, squid-cat requested changes
### Good
- コンポーネントが使えてて良い！
- 形は合ってるので、後は壁打ちするのみ
- ラジオボタンの実装は結構大変だけど、いい所まで来てる

### Next
- フォルダを移動したい
  - `components` → `src/components`
  - `interfaces` → `src/interfaces`
- propsは引数のtypeを決定するものに命名しよう！

### Q&A
> コンポーネントに返り値という概念があるか

恐らくだけど、comboで選択されているものを子コンポーネント→親コンポーネントに渡してあげたいってことだよね？
それだったら、親コンポーネントに
```ts
const [selectedItem, setSelectedItem] = useState();
```
を定義してあげて、子コンポーネントで受け取るpropsのtypeに
```ts
setItem(item: string): void;
```
を設定して、子コンポーネントで
```ts
props.setItem("item名");
```
を呼び出してあげると良さそう！
**（説明が難しすぎるので、これはハンズオン形式でやりましょう）**

> idやhtmlForの使い方が正しいか
#### idについて
今回の場合、idは特になくてもいいかなとは思ったかな
idを使用して何かを使用して何かをするってことは無さそうなので、消しても良さそう？

#### htmlForについて
初めて知った！合ってるか分からないけど、見た感じは良さそう！
自分も今後使ってみたい

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +import styled from "styled-components"
typescriptで書いてるので、モジュールに型が付くものもインストールしましょう
`yarn add @types/styled-components`

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +          </>
```suggestion
          <div key={comboList.id}>
            <InputRadioItemProps 
            name={props.name}  
            type="radio" 
            id={"combo__"+comboList.id}
            onChange={()=>(onHandleChange(comboList.id))}
            >              
            </InputRadioItemProps>
            <LabelItemProps 
            htmlFor={"combo__"+comboList.id}
            >{comboList.id}:{comboList.name}
            </LabelItemProps>
          </div>
```

mapで同じものを複数生成する場合は、その下のタグに`key={<DOMの識別が付くような任意の数字>}`を付けてあげてください！

2023-03-03 00:24 UTC, squid-cat commented on interfaces/index.ts
>  }
propsはexportする必要はないと思うので、使うコンポーネントにtypesを宣言してその中でだけ使用するようにしたい

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +const BtnOkProps = styled.button`
propsは引数っていう意味だから、ここからは外そう

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +`;
propsは引数っていう意味だから、ここからは外そう

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +const InputRadioItemProps = styled.input`
propsは引数っていう意味だから、ここからは外そう

2023-03-03 00:24 UTC, squid-cat commented on interfaces/index.ts
>  export type ComboListProps = {
```suggestion
export type ComboList= {
```

propsは引数っていう意味だから、なくても良さそう

2023-03-03 00:24 UTC, squid-cat commented on src/pages/index.tsx
> +      <Combo key={"aaa"} name={"aaa"} data={data} length={data.length} />
```suggestion
      <Combo name={"aaa"} data={data} length={data.length} />
```

特に意味が無ければ消しちゃって良さそう

2023-03-03 00:24 UTC, squid-cat commented on components/selectList/combo.tsx
> +    console.log(selId);
消しても良いかも！
（上げるときにconsole.logがあるかチェックするやつ導入したいね）

2023-03-03 11:32 UTC, KadoProG reviewed
すべて確認しました

2023-03-03 11:53 UTC, squid-cat commented
終わったら以下の記事の7番を参考にして、再度レビュー依頼して！
https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

これからの新しいPRを作成した場合も、上の手順でレビュー依頼してくれると助かる！

（ペアプロして欲しかったらdiscordで声掛けて！）

2023-03-04 00:40 UTC, squid-cat approved these changes

2023-03-04 00:40 UTC, squid-cat commented on src/components/selectList/combo.tsx
> +        </div>
あわよくば、これもコンポーネント化したい

2023-03-04 01:41 UTC, squid-cat approved these changes

2023-03-07 22:58 UTC, squid-cat commented
あくまでもこのブランチは「ラジオボタンコンポーネントの作成」だから、それ以外は別ブランチで分けて欲しい！

変更履歴が多すぎて見るのが大変なんよね

2023-03-08 01:11 UTC, merged

2023-03-08 02:46 UTC, squid-cat reviewed
おおよそOKな気がします！
コードのコメントアウトだけ、不要なものは消してしまいましょう
（文字化しないと、コード見て理解するまでに時間がかかる）

2023-03-08 02:46 UTC, squid-cat commented on src/components/selectList/combo.tsx
> +
不要なコメントは何したいか忘れてしまうのでマージする前に消しておこう

どうしても必要な場合は

`// fix: 〇〇を動作させるように修正`

のようなコメントが欲しいかな

2023-03-08 02:46 UTC, squid-cat commented on src/components/selectList/combo.tsx
> +      /> */}
不要なコメントは消しちゃおう

2023-03-08 02:46 UTC, squid-cat commented on src/components/selectList/comboList.tsx
> +// `;
不要なコメントは消しちゃおう

2023-03-08 02:46 UTC, squid-cat commented on src/components/selectList/comboList.tsx
> +      {/* <BtnOk>OK</BtnOk> */}
不要なコメントは消しちゃおう

2023-03-08 02:46 UTC, squid-cat commented on src/pages/index.tsx
> +      </p> */}
同文

2023-03-08 02:46 UTC, squid-cat commented on src/pages/index.tsx
> +      </p> */}
同文

2023-03-08 02:46 UTC, squid-cat commented on src/pages/questionnaire/index.tsx
> +      </p> */}
同文

2023-03-08 02:46 UTC, squid-cat commented on src/pages/questionnaire/index.tsx
> +      </p> */}
同文

2023-03-08 02:46 UTC, squid-cat commented on src/pages/questionnaire/index.tsx
> +  // }, [selectedItem]);
同文

2023-03-08 02:46 UTC, squid-cat commented on src/pages/questionnaire/index.tsx
> +// const inter = Inter({ subsets: ["latin"] });
同文